#!/usr/bin/env python3
"""
plugin/scripts/paper_weekly_show.py — researcher-facing read of the latest
weekly recommendation batch (operator-side generated by
scripts/archive/weekly_recommend.py and persisted to
csnl_paper_rec.archive_weekly_picks).

Read-only. No DB writes. Korean output.

Usage:
    python3 plugin/scripts/paper_weekly_show.py JOP
    python3 plugin/scripts/paper_weekly_show.py JOP --week 2026-W22
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

from _pdb import load_env, query, schema  # noqa: E402


def _iso_week(date: _dt.date) -> str:
    y, w, _ = date.isocalendar()
    return f"{y}-W{w:02d}"


def _first_author(authors_json) -> str:
    if not authors_json:
        return ""
    if isinstance(authors_json, str):
        try:
            authors_json = json.loads(authors_json)
        except (ValueError, TypeError):
            return ""
    if not isinstance(authors_json, list) or not authors_json:
        return ""
    a = authors_json[0]
    if isinstance(a, str):
        return a
    if isinstance(a, dict):
        if a.get("name"):
            return str(a["name"])
        fam = a.get("family") or a.get("surname")
        giv = a.get("given") or a.get("first")
        if fam and giv:
            return f"{giv} {fam}"
        return str(fam or giv or "")
    return ""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("researcher")
    ap.add_argument("--week", default=None)
    args = ap.parse_args()

    load_env()
    rid = args.researcher.strip().upper()
    week = args.week or _iso_week(_dt.date.today())
    sch = schema()

    rows = query(
        f"SELECT w.rank, w.canonical_id, w.composite, w.why_ko, "
        f"       p.title, p.year, p.authors_json, p.venue "
        f"FROM {sch}.archive_weekly_picks w "
        f"JOIN {sch}.archive_papers p ON p.canonical_id = w.canonical_id "
        f"WHERE w.researcher_id = %s AND w.week_iso = %s "
        f"ORDER BY w.rank ASC",
        (rid, week),
    )

    if not rows:
        print(f"## {rid} — {week}")
        print()
        print("이번 주 추천이 아직 생성되지 않았습니다.")
        print("운영자의 화요일 저녁 cron 이후 다시 시도하시거나,")
        print("`/csnl-paper-archive-interview:paper-interview {0}` 로 ".format(rid)
              + "지금 바로 인터뷰를 시작하실 수 있습니다.")
        return 0

    print(f"## {rid} — {week} 추천 ({len(rows)}편)\n")
    for r in rows:
        title = (r.get("title") or "").strip() or "(제목 없음)"
        year = r.get("year") or "----"
        first = _first_author(r.get("authors_json"))
        venue = (r.get("venue") or "").strip()
        meta = " / ".join(x for x in (first, venue) if x)
        head = f"{r['rank']}. **{title}** ({year})"
        if meta:
            head += f" — {meta}"
        print(head)
        why = (r.get("why_ko") or "").strip() or "관심 phrase 매칭"
        print(f"   - 추천 근거: {why}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
