#!/usr/bin/env python3
"""
plugin/scripts/paper_blitz_show.py — researcher-facing read of the upcoming
Wednesday Paper Blitz assignment (operator-side generated by
scripts/archive/paper_blitz_feed.py and persisted to
csnl_paper_rec.archive_paper_blitz).

Read-only. No DB writes. Korean output.

Usage:
    python3 plugin/scripts/paper_blitz_show.py JOP
    python3 plugin/scripts/paper_blitz_show.py JOP --date 2026-05-27
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

from _pdb import load_env, query, schema  # noqa: E402


def _next_wednesday(today: _dt.date) -> _dt.date:
    return today + _dt.timedelta(days=(2 - today.weekday()) % 7)


def _first_author(authors_json) -> str:
    if not authors_json:
        return ""
    if isinstance(authors_json, str):
        try:
            authors_json = json.loads(authors_json)
        except (ValueError, TypeError):
            return ""
    if not isinstance(authors_json, list) or not authors_json:
        return ""
    a = authors_json[0]
    if isinstance(a, str):
        return a
    if isinstance(a, dict):
        if a.get("name"):
            return str(a["name"])
        fam = a.get("family") or a.get("surname")
        giv = a.get("given") or a.get("first")
        if fam and giv:
            return f"{giv} {fam}"
        return str(fam or giv or "")
    return ""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("researcher")
    ap.add_argument("--date", default=None, help="YYYY-MM-DD (default: next Wed)")
    args = ap.parse_args()

    load_env()
    rid = args.researcher.strip().upper()
    blitz_date = (
        _dt.date.fromisoformat(args.date) if args.date
        else _next_wednesday(_dt.date.today())
    )
    sch = schema()

    rows = query(
        f"SELECT b.slot_order, b.canonical_id, b.status, "
        f"       p.title, p.year, p.authors_json, p.venue, p.doi "
        f"FROM {sch}.archive_paper_blitz b "
        f"JOIN {sch}.archive_papers p ON p.canonical_id = b.canonical_id "
        f"WHERE b.presenter = %s AND b.blitz_date = %s "
        f"ORDER BY b.slot_order ASC",
        (rid, blitz_date.isoformat()),
    )

    if not rows:
        print(f"## {rid} — Paper Blitz {blitz_date.isoformat()} (수)\n")
        print("이번 주 발표 배정 없음.")
        print()
        print("지난 1주간 인터뷰에서 `이미 읽음`으로 표시하신 paper 가 없어")
        print(f"이번 수요일 Paper Blitz 발표가 배정되지 않았습니다.")
        print(f"`/csnl-paper-archive-interview:paper-interview {rid}` 로 ")
        print("인터뷰를 진행하시면 다음 주 발표 후보가 자동 생성됩니다.")
        return 0

    print(f"## {rid} — Paper Blitz {blitz_date.isoformat()} (수)\n")
    for r in rows:
        title = (r.get("title") or "").strip() or "(제목 없음)"
        year = r.get("year") or "----"
        first = _first_author(r.get("authors_json"))
        venue = (r.get("venue") or "").strip()
        meta = " / ".join(x for x in (first, venue) if x)
        head = f"슬롯 {r['slot_order']}: **{title}** ({year})"
        if meta:
            head += f" — {meta}"
        print(head)
        if r.get("doi"):
            print(f"   DOI: {r['doi']}")
        print(f"   상태: {r.get('status') or 'scheduled'}")
    print()
    print("발표 분량: 5분 + 토론. 핵심 주장 / 방법 / 결과 / 본인 연구와의 연결 순으로 준비하시면 좋습니다.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
