-- state/schema_v3.sql — RETIRED. Tombstone only: this file defines NO objects.
--
-- QUARANTINED BY P32 (2026-06-12) — DO NOT RECREATE.
-- This file used to hold the v3 Slack-cron pipeline extensions:
--     cycle_state    (per-(cycle_id, member_init) state machine)
--     evolution_log  (rule-based end-of-cycle evolution audit)
--   + ix_cycle_state_state / ix_cycle_state_cycle / ix_evol_cycle
--
-- P32 verified both tables 0-row / 0-live-code-reference / 0-FK / 0-view-
-- dependency and renamed them `cycle_state_dead` / `evolution_log_dead` in
-- the ledger. Their create-if-not-exists blocks were left here by mistake,
-- so any `python3 scripts/init_db.py` run silently RESURRECTED both
-- under their original names (and init_db's verifier demanded them). The DDL
-- is removed here to end that drift; scripts/init_db.py no longer applies
-- this file at all.
--
-- The only remaining consumers of these two tables are the already-retired
-- Slack scripts under scripts/_legacy/ (cron_tick.py, apply_evolution.py,
-- run_weekly_cron.sh, run_evolution_cron.sh). They are not wired to any live
-- path; the P23 Notion delivery harness replaced them.
--
-- Do NOT re-add DDL here. Reviving the v3 cron path requires an explicit,
-- operator-approved migration under state/migrations/ (and a decision on
-- whether to rename the `*_dead` tables back rather than create empty ones).
-- Everything above is reversible via git history for this file.
